### ISSUE TITLE
OTIS: Importer stops when POI not found

### ISSUE THREAD

**Issue by mhull** [thinkshout/wp-otis#51]
I am having issues with the "Sync All Poi's" process not completing and getting stuck mid-sync. I realized that this line of code is what was keeping it from completing.

https://github.com/thinkshout/wp-otis/blob/a4d8ccff2c3a43e95afc17f9290f00a21cf49cdc/src/Otis_Importer.php#L366

It doesn't seem like a single POI going missing should abort the entire syncing process. As a workaround, I commented out the line of code and just did a `return` so that the rest of the POI's after the missing one could sync.

Is there a possibility that this can be addressed in a future version - that an error can be flagged or logged somehow without aborting the entire process? If so, that would be much appreciated!

**Comment by aletamelton** [comment]
@mhull We have added this issue to our next release.

**Comment by mhull** [comment]
Awesome, thank you so much!

**Comment by BrendanJercich** [comment]
@mshaver Nope, you are correct, this will be fixed in the release.
