### ISSUE TITLE
OTIS: Investigation for missing city parameters

### ISSUE THREAD

**Issue by BrendanJercich** [thinkshout/wp-otis#56]
On one DMO site, after updating to 1.2.5.1, the city parameters are not being passed in with requests to OTIS. This is not the case with TO's Wordpress testing platform for OTIS, so there may be a difference in configuration that is to blame, or it may be an order-of-operations issue where (eg) city entities need to be fetched before the full sync. This ticket left open to determine whether this needs a change in code or an update to documentation to prevent the issue in future.

**Comment by BrendanJercich** [comment]
Possible ideas: maybe name of city parameter has changed at some point? Brendan see TROR issue 1724

**Comment by monicapatel21** [comment]
Two weeks ago is when we met with Cardwell so we are testing to see what we can learn about this on the Tillamook Chamber sandbox site we got access to from Jeff.

**Comment by BrendanJercich** [comment]
According to the example at https://otis.traveloregon.com/fe_docs/specification.html#create-a-filterset the `city` parameter name should still be correct.

**Comment by mshaver** [comment]
@BrendanJercich anything more we need on this ticket? Can we close?

**Comment by BrendanJercich** [comment]
@mshaver To the best of my knowledge this issue is no longer happening, so yes, we can close it out.

**Comment by mshaver** [comment]
Thanks @BrendanJercich
