### ISSUE TITLE
OTIS: Synchronize versioning strings

### ISSUE THREAD

**Issue by BrendanJercich** [thinkshout/wp-otis#57]
Before the next release of the plugin, all designations of the plugin version need to be updated and identical. Right now the known places to change are:

- [x] wp_register_script and wp_enqueue_style in Otis_Dashboard.php
- [x] version comment in wp-otis.php
- [x] version declaration in README.md
- [x] Determine where and how the user-agent string is being set, because that also has a version string appended

**Comment by mshaver** [comment]
@BrendanJercich can this be closed out?

**Comment by BrendanJercich** [comment]
@mshaver yes, this will go out whenever we make a release out of the deletion fix we put together for Cardwell.
